//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Japanese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Japanese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Japanese", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英語&gt;日本語.
        /// </summary>
        internal static string catEngToJpn {
            get {
                return ResourceManager.GetString("catEngToJpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語&gt;英語.
        /// </summary>
        internal static string catJpnToEng {
            get {
                return ResourceManager.GetString("catJpnToEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テストのPayPal払い戻し.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支払方法.
        /// </summary>
        internal static string headerMethod {
            get {
                return ResourceManager.GetString("headerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品のカテゴリー.
        /// </summary>
        internal static string mnCategory {
            get {
                return ResourceManager.GetString("mnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東京本社 〒105-0013東京都港区浜松町2-1-3 第二森ビル4階.
        /// </summary>
        internal static string mnCompany {
            get {
                return ResourceManager.GetString("mnCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お問い合わせ.
        /// </summary>
        internal static string mnContact {
            get {
                return ResourceManager.GetString("mnContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        internal static string mnFaq {
            get {
                return ResourceManager.GetString("mnFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トランザクション履歴.
        /// </summary>
        internal static string mnTrans {
            get {
                return ResourceManager.GetString("mnTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申し訳ありませんが、私たちは今の現金を受け入れていません。.
        /// </summary>
        internal static string msg1 {
            get {
                return ResourceManager.GetString("msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功！.
        /// </summary>
        internal static string msg2 {
            get {
                return ResourceManager.GetString("msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書番号の払い戻し取引.
        /// </summary>
        internal static string msg3 {
            get {
                return ResourceManager.GetString("msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $10.
        /// </summary>
        internal static string price1 {
            get {
                return ResourceManager.GetString("price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $30.
        /// </summary>
        internal static string price2 {
            get {
                return ResourceManager.GetString("price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $50.
        /// </summary>
        internal static string price3 {
            get {
                return ResourceManager.GetString("price3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現金.
        /// </summary>
        internal static string tabCash {
            get {
                return ResourceManager.GetString("tabCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string tabPaypal {
            get {
                return ResourceManager.GetString("tabPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペイパルのPaypal.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低価格.
        /// </summary>
        internal static string txt1 {
            get {
                return ResourceManager.GetString("txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセルポリシー.
        /// </summary>
        internal static string txt2 {
            get {
                return ResourceManager.GetString("txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お支払い.
        /// </summary>
        internal static string txt3 {
            get {
                return ResourceManager.GetString("txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax: 81-3-3433-3320.
        /// </summary>
        internal static string txtFax {
            get {
                return ResourceManager.GetString("txtFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 払い戻し.
        /// </summary>
        internal static string txtRefund {
            get {
                return ResourceManager.GetString("txtRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel: 81-3-5733-4264.
        /// </summary>
        internal static string txtTel {
            get {
                return ResourceManager.GetString("txtTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引.
        /// </summary>
        internal static string txtTrans {
            get {
                return ResourceManager.GetString("txtTrans", resourceCulture);
            }
        }
    }
}
